INSERT INTO GENRES (ID, NAME) VALUES (1,'Комедия');
INSERT INTO GENRES (ID, NAME) VALUES (2,'Драма');
INSERT INTO GENRES (ID, NAME) VALUES (3,'Мультфильм');
INSERT INTO GENRES (ID, NAME) VALUES (4,'Триллер');
INSERT INTO GENRES (ID, NAME) VALUES (5,'Документальный');
INSERT INTO GENRES (ID, NAME) VALUES (6,'Боевик');


INSERT INTO RATINGS (ID, NAME) VALUES (1,'G');
INSERT INTO RATINGS (ID, NAME) VALUES (2,'PG');
INSERT INTO RATINGS (ID, NAME) VALUES (3,'PG-13');
INSERT INTO RATINGS (ID, NAME) VALUES (4,'R');
INSERT INTO RATINGS (ID, NAME) VALUES (5,'NC-17');


/*
SELECT * FROM FILMS;
SELECT * FROM USERS;
SELECT * FROM FILM_RATING;
select * from users_like; //where film_id=1;
select * from films where id = 1;
SELECT * FROM FILM_GENRE;
SELECT * FROM GENRES;
SELECT * FROM FILM_RATING;
SELECT * FROM FILM_GENRE INNER JOIN GENRES G on FILM_GENRE.GENRES_ID = G.ID
WHERE FILM_ID=2;
SELECT * FROM FILM_RATING INNER JOIN RATINGS R on FILM_RATING.RATINGS_ID = R.ID;
         //WHERE FILM_ID =?

 */


























