DELETE FROM USER_FRIENDS;
ALTER TABLE USER_FRIENDS ALTER COLUMN ID RESTART WITH 1;
DELETE FROM USERS;
ALTER TABLE USERS ALTER COLUMN id RESTART WITH 1;
DELETE FROM USERS_LIKE;
ALTER TABLE USERS_LIKE ALTER COLUMN ID RESTART WITH 1;
DELETE FROM FILM_GENRE;
ALTER TABLE FILM_GENRE ALTER COLUMN ID RESTART WITH 1;
DELETE FROM GENRES ;
ALTER TABLE GENRES ALTER COLUMN ID RESTART WITH 1;
DELETE FROM RATINGS ;
ALTER TABLE RATINGS ALTER COLUMN ID RESTART WITH 1;
DELETE FROM FILM_RATING ;
ALTER TABLE FILM_RATING ALTER COLUMN ID RESTART WITH 1;
DELETE FROM FILMS ;
ALTER TABLE FILMS ALTER COLUMN ID RESTART WITH 1;


INSERT INTO GENRES (ID, NAME) VALUES (1,'Комедия');
INSERT INTO GENRES (ID, NAME) VALUES (2,'Драма');
INSERT INTO GENRES (ID, NAME) VALUES (3,'Мультфильм');
INSERT INTO GENRES (ID, NAME) VALUES (4,'Триллер');
INSERT INTO GENRES (ID, NAME) VALUES (5,'Документальный');
INSERT INTO GENRES (ID, NAME) VALUES (6,'Боевик');


INSERT INTO RATINGS (ID, NAME) VALUES (1,'G');
INSERT INTO RATINGS (ID, NAME) VALUES (2,'PG');
INSERT INTO RATINGS (ID, NAME) VALUES (3,'PG-13');
INSERT INTO RATINGS (ID, NAME) VALUES (4,'R');
INSERT INTO RATINGS (ID, NAME) VALUES (5,'NC-17');


/*
SELECT * FROM FILMS;
SELECT * FROM USERS;
SELECT * FROM FILM_RATING;
select * from users_like; //where film_id=1;
select * from films where id = 1;
SELECT * FROM FILM_GENRE;
SELECT * FROM FILM_RATING;

 */




















