
INSERT INTO USERS (email, login, name, birthday) VALUES ('mmail@mail.ru', 'Kirry',
'rihanna', '2022-03-28');

INSERT INTO USERS (email, login, name, birthday) VALUES ('22mmail@mail.ru', '22Kirry',
                                                         '22rihanna', '2022-03-28');

INSERT INTO USERS (email, login, name, birthday) VALUES ('333mmail@mail.ru', '33Kirry',
                                                         '33rihanna', '332022-03-28');
SELECT * FROM USERS;
delete  from users where id IN (11,12,13);
SELECT * FROM USER_FRIENDS;
select friend_id from user_friends where user_id =1;
select FRIEND_ID from USER_FRIENDS WHERE USER_ID = 1 INTERSECT SELECT FRIEND_ID from USER_FRIENDS WHERE USER_ID =2;

INSERT INTO USER_FRIENDS (USER_ID, FRIEND_ID) VALUES (1,2);
INSERT INTO USER_FRIENDS (USER_ID, FRIEND_ID) VALUES (1,3);
INSERT INTO USER_FRIENDS (USER_ID, FRIEND_ID) VALUES (2,3);
//1 users add friends 2 n 3
SELECT USERS.ID, USER_FRIENDS.FRIEND_ID FROM USERS LEFT JOIN USER_FRIENDS ON USERS.ID = USER_FRIENDS.USER_ID  WHERE USER_ID=1;

INSERT INTO USER_REQUEST (USER_ID, FRIEND_ID) VALUES (1,3);

INSERT INTO GENRES (ID, NAME) VALUES (1,'Комедия');
INSERT INTO GENRES (ID, NAME) VALUES (2,'Драма');
INSERT INTO GENRES (ID, NAME) VALUES (3,'Мультфильм');
INSERT INTO GENRES (ID, NAME) VALUES (4,'Триллер');
INSERT INTO GENRES (ID, NAME) VALUES (5,'Документальный');
INSERT INTO GENRES (ID, NAME) VALUES (6,'Боевик');
SELECT  * FROM GENRES;

INSERT INTO RATINGS (ID, NAME) VALUES (1,'G');
INSERT INTO RATINGS (ID, NAME) VALUES (2,'PG');
INSERT INTO RATINGS (ID, NAME) VALUES (3,'PG-13');
INSERT INTO RATINGS (ID, NAME) VALUES (4,'R');
INSERT INTO RATINGS (ID, NAME) VALUES (5,'NC-17');
SELECT  * FROM RATINGS;



INSERT INTO FILMS (NAME, DESCRIPTION, RELEASE_DATE, DURATION) VALUES (
'film1', 'desc1', '2022-03-28', 90);

INSERT INTO FILMS (NAME, DESCRIPTION, RELEASE_DATE, DURATION) VALUES (
'film2', 'desc2', '2022-03-28', 100);

INSERT INTO FILMS (NAME, DESCRIPTION, RELEASE_DATE, DURATION) VALUES (
'film3', 'desc3', '2022-03-28', 120);

SELECT  * FROM FILMS;

INSERT INTO USERS_LIKE (USER_ID, FILM_ID) VALUES (1,1);
INSERT INTO USERS_LIKE (USER_ID, FILM_ID) VALUES (1,2);
INSERT INTO USERS_LIKE (USER_ID, FILM_ID) VALUES (1,3);
INSERT INTO USERS_LIKE (USER_ID, FILM_ID) VALUES (2,3);

SELECT  * FROM USERS_LIKE;

SELECT FILMS.ID, USERS_LIKE.USER_ID
FROM FILMS
LEFT JOIN USERS_LIKE ON USERS_LIKE.FILM_ID = FILMS.ID
WHERE FILMS.ID = 1;

delete  from FILM_GENRE where id IN (1,2,3,4,5);
INSERT INTO FILM_GENRE(FILM_ID, GENRES_ID) VALUES (1,4);
INSERT INTO FILM_GENRE(FILM_ID, GENRES_ID) VALUES (2,1);
INSERT INTO FILM_GENRE(FILM_ID, GENRES_ID) VALUES (3,5);

SELECT * FROM FILM_GENRE;

SELECT FILM_GENRE.FILM_ID, GENRES.NAME
FROM FILM_GENRE
LEFT JOIN GENRES ON FILM_GENRE.GENRES_ID = GENRES.ID
WHERE FILM_ID = 1;
//LEFT JOIN FILMS ON FILM_GENRE.FILM_ID = FILMS.ID;
INSERT INTO FILM_RATING(RATINGS_ID, FILM_ID) VALUES (2,1);
INSERT INTO FILM_RATING(RATINGS_ID, FILM_ID) VALUES (3,1);
INSERT INTO FILM_RATING(RATINGS_ID, FILM_ID) VALUES (4,2);
INSERT INTO FILM_RATING(RATINGS_ID, FILM_ID) VALUES (1,3);

SELECT FILM_RATING.FILM_ID, RATINGS.NAME
FROM FILM_RATING
LEFT JOIN RATINGS ON FILM_RATING.RATINGS_ID = RATINGS.ID
WHERE FILM_ID = 1;

SELECT * FROM USERS;












